HospitalPharmacyManagementSystem.Web/Controllers/PharmacistController.cs
namespace HospitalPharmacyManagementSystem.Web.Controllers
{
    using HospitalPharmacyManagementSystem.Services.Data;
    using HospitalPharmacyManagementSystem.Services.Data.Interfaces;
    using HospitalPharmacyManagementSystem.Web.ViewModels.Drug;
    using HospitalPharmacyManagementSystem.Web.ViewModels.Pharmacist;
    using HospitalPharmacyManagementSytem.Web.Infrastucture.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using static Common.NotificationMessages;


    [Authorize]
    public class PharmacistController : Controller
    {
        private readonly IPharmacistService pharmacistService;
        private readonly IDrugService drugService;
        private readonly IDiseaseService diseaseService;

        public PharmacistController(IPharmacistService pharmacistService, IDrugService drugService, IDiseaseService diseaseService)
        {
            this.pharmacistService = pharmacistService;
            this.drugService = drugService;
            this.diseaseService = diseaseService;
        }

        [HttpGet]
        public async Task<IActionResult> BecomePharmacist()
        {
            string userId = this.User.GetId()!;
            bool isPharmacist = await this.pharmacistService.PharmacistExistsByUserIdAsync(userId);

            if (isPharmacist)
            {
                this.TempData[ErrorMessage] = "You are already a partner!";
                return this.RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> BecomePharmacist(BecomePharmacistFormModel model)
        {
            string userId = this.User.GetId()!;
            bool isPharmacist = await this.pharmacistService.PharmacistExistsByUserIdAsync(userId);

            if (isPharmacist)
            {
                this.TempData[ErrorMessage] = "You are already a partner!";
                return this.RedirectToAction("Index", "Home");
            }

            bool isIdTaken = await 
                this.pharmacistService.PharmacistExistsByHospitalIdAsync(model.HospitalIdNumber);
            if (isIdTaken)
            {
                ModelState.AddModelError(nameof(model.HospitalIdNumber),
                    "Pharmacist with the provided Hospital ID already exists!");
            }

            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await this.pharmacistService.Create(userId, model);
            }
            catch (Exception)
            {
                this.TempData[ErrorMessage] = "Unexpected error occured while attempting to register you as a partner! " +
                    "Please try again later or contact administrator!";

                return this.RedirectToAction("Index", "Home");
            }

            return this.RedirectToAction("All", "Drug");
        }

        [HttpGet]
        public async Task<IActionResult> Prescribe()
        {
            string userId = this.User.GetId()!;
            bool isUserPharmacist = await this.pharmacistService
                .PharmacistExistsByUserIdAsync(userId);
            //ViewBag.IsUserPharmacist = isUserPharmacist;

            try
            {
                PrescribeFormModel model = new PrescribeFormModel
                {
                    Drugs = await this.drugService.AllDrugsAsync(),
                    Diseases = await this.diseaseService.AllDiseasesAsync()
                };

                return View(model);
            }
            catch (Exception)
            {
                this.ModelState.AddModelError(string.Empty,
                    "Unexpected error occurred while trying to update the drug!" +
                    "Please try again or contact administrator!");
                return this.RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Prescribe(/*string id, */PrescribeFormModel model)
        {
            //bool drugExists = await this.drugService
            //    .ExistsByIdAsync(id);
            string userId = this.User.GetId()!;
            bool isUserPharmacist = await this.pharmacistService
                .PharmacistExistsByUserIdAsync(userId);
            ViewBag.IsUserPharmacist = isUserPharmacist;

            bool userExists = await
                this.pharmacistService.PatientExistsByEmailAsync(model.PatientEmail);

            if (!userExists)
            {
                ModelState.AddModelError(nameof(model.PatientEmail),
                    "Patient with the provided email does not exist in the system!");
            }

            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            try
            {


                string? pharmacistId =
                   await this.pharmacistService.GetPharmacistIdByUserIdAsync(this.User.GetId()!);

                TempData[SuccessMessage] = "Prescription was added successfully!";
                await this.pharmacistService.PrescribeDrugAsync(model, userId);
            }
            catch (Exception)
            {
                this.TempData[ErrorMessage] = "Unexpected error occured while attempting to prescribe the drug! " +
                    "Please try again later or contact administrator!";

                return this.RedirectToAction("Index", "Home");
            }

            return RedirectToAction("All", "Drug");
        }
    }
}

HospitalPharmacyManagementSystem.Web/Controllers/PrescriptionController.cs
using HospitalPharmacyManagementSystem.Services.Data.Interfaces;
using HospitalPharmacyManagementSystem.Web.ViewModels.Pharmacist;
using HospitalPharmacyManagementSytem.Web.Infrastucture.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static HospitalPharmacyManagementSystem.Common.NotificationMessages;


namespace HospitalPharmacyManagementSystem.Web.Controllers
{
    [Authorize]
    public class PrescriptionController : Controller
    {
        private readonly IPharmacistService pharmacistService;
        private readonly IDrugService drugService;

        public PrescriptionController(IPharmacistService pharmacistService, IDrugService drugService)
        {
            this.pharmacistService = pharmacistService;
            this.drugService = drugService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> PrescriptionDetails(string id)
        {
            //bool drugExists = await this.drugService.ExistsByIdAsync(id);
            string userId = this.User.GetId()!;
            bool isUserPharmacist = await this.pharmacistService
                .PharmacistExistsByUserIdAsync(userId);
            ViewBag.IsUserPharmacist = isUserPharmacist;

            //if (!drugExists)
            //{
            //    this.TempData[ErrorMessage] = "Drug with the provided id does not exist!";
            //    return this.RedirectToAction("All", "Drug");
            //}

            try
            {
                PrescriptionViewModel viewModel = await this.drugService
                .GetPrescriptionByIdAsync(id);

                return View(viewModel);
            }
            catch (Exception)
            {
                this.TempData[ErrorMessage] = "Unexpected error occurred while trying to update the drug!" +
                    "Please try again or contact administrator!";
                return this.RedirectToAction("All", "Drug");
            }
        }
    }
}

HospitalPharmacyManagementSystem.Web/Views/Shared/_DrugFormPartial.cshtml
@using HospitalPharmacyManagementSystem.Common.Enums;
@model AddDrugViewModel
<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="BrandName" style="font-weight:500"></label>
                <input asp-for="BrandName" class="form-control" placeholder="Brand Name" style="background-color:#e1eedd">
                <span asp-validation-for="BrandName" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" style="font-weight:500"></label>
                <textarea asp-for="Description" rows="4" class="form-control"
                          placeholder="Drug Descpription" style="background-color:#e1eedd"></textarea>
                <span asp-validation-for="Description" class="small textdanger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" style="font-weight:500"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Drug Image Link" style="background-color:#e1eedd">
                <span asp-validation-for="ImageUrl" class="small textdanger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PricePerPackage" style="font-weight:500"></label>
                <input asp-for="PricePerPackage" class="form-control" style="background-color:#e1eedd">
                <span asp-validation-for="PricePerPackage" class="small textdanger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DrugForm" style="font-weight:500"></label>
                <select asp-for="DrugForm" class="form-control" style="background-color:#e1eedd">
                    @foreach (int formValue in System.Enum.GetValues(typeof(DrugForm)))
                    {
                        <option value="@formValue">@((DrugForm)formValue)</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="small textdanger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" style="font-weight:500"></label>
                <select asp-for="CategoryId" class="form-control" style="background-color:#e1eedd;">
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="small textdanger"></span>
            </div>
            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" style="color: white; background-color:#183a1d;font-weight:500" />
            </div>
        </form>
    </div>
</div>

HospitalPharmacyManagementSystem.Web/Views/Shared/_DrugPartial.cshtml
@using HospitalPharmacyManagementSystem.Services.Data.Interfaces
@using HospitalPharmacyManagementSystem.Services.Data;
@using HospitalPharmacyManagementSytem.Web.Infrastucture.Extensions;
@model DrugAllViewModel


@inject IPharmacistService PharmacistService
@{
    bool isUserPharmacist = await PharmacistService.PharmacistExistsByUserIdAsync(this.User.GetId());
}

<div class="col-md-4">
    <div class="card mb-3" style="background-color:#e1eedd">
        <img class="card-img-top" src="@Model.ImageUrl" style="width:200px;height: 200px;" alt="Drug Image">
        <div class="card-body text-center" style="background-color:#e1eedd">
            <h4>@Model.BrandName</h4>
            <h6>
                Price:
                <b>@($"{Model.Price:f2}") BGN</b>
            </h6>
            <br />
            <a asp-area="" asp-controller="Drug" asp-action="Details" asp-route-id="@Model.Id"
               class="btn btn-success" style="color: white; background-color:#183a1d;font-weight:500">Details</a>

            @if (User.Identity?.IsAuthenticated ?? false)
            {
                @if (isUserPharmacist)
                {
                    <a asp-area="" asp-controller="Drug" asp-action="Edit" asp-route-id="@Model.Id"
                       class="btn btn-warning" style="color: white; background-color:#183a1d;font-weight:500">Edit</a>
                    <a asp-area="" asp-controller="Drug" asp-action="Delete" asp-route-id="@Model.Id"
                       class="btn btn-danger" style="color: white; background-color:#183a1d;font-weight:500">Delete</a>
                }
            }
        </div>
    </div>
</div>

HospitalPharmacyManagementSystem.Web/Views/Shared/_Layout.cshtml
@using static HospitalPharmacyManagementSystem.Common.GeneralAppConstants
@using HospitalPharmacyManagementSystem.Services.Data.Interfaces
@using HospitalPharmacyManagementSytem.Web.Infrastucture.Extensions;

@inject IPharmacistService PharmacistService
@{
    bool isUserPharmacist = await PharmacistService.PharmacistExistsByUserIdAsync(this.User.GetId());
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DrugWise</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HospitalPharmacyManagementSystem.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/pictures/mainLogo.png" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body style="background-color:#fefbe9;">
    <partial name="_NotificationsPartial"/>
    <header style="background-color:#e1eedd">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" style="color: #f0a04b ; font-family: Garamond, serif; font-size: 28px"
                   asp-area="" asp-controller="Home" asp-action="Index"><strong>DrugWise</strong></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" style="font-family: 'Times New Roman', serif; font-size: 20px"
                               asp-area="" asp-controller="Drug" asp-action="All"><b>All Drugs</b></a>
                        </li>
                        @if (this.User.Identity?.IsAuthenticated ?? false)
                        {
                            @if (isUserPharmacist)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Drug" asp-action="Add">Add Drug</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Pharmacist" asp-action="Prescribe">Add Prescription</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Drug" asp-action="Mine">My Prescriptions</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="background-color:#e1eedd" class="border-top footer text-muted">
        <div class="container">
            &copy; <b>DrugWise @ReleaseYear</b>
            @if (DateTime.UtcNow.Year != ReleaseYear)
            {
                @Html.Raw($" - {DateTime.UtcNow.Year}")
            }
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HospitalPharmacyManagementSystem.Web/Views/Shared/_NotificationsPartial.cshtml
@using static HospitalPharmacyManagementSystem.Common.NotificationMessages;

@if(TempData.ContainsKey(ErrorMessage))
{
    <script>toastr.error('@TempData[ErrorMessage]');</script>
}

@if (TempData.ContainsKey(WarningMessage))
{
    <script>toastr.warning('@TempData[WarningMessage]');</script>
}

@if (TempData.ContainsKey(InformationMessage))
{
    <script>toastr.info('@TempData[InformationMessage]');</script>
}

@if (TempData.ContainsKey(SuccessMessage))
{
    <script>toastr.success('@TempData[SuccessMessage]');</script>
}

HospitalPharmacyManagementSystem.Web/Views/Shared/_PrescriptionPartial.cshtml
@using HospitalPharmacyManagementSystem.Services.Data.Interfaces
@using HospitalPharmacyManagementSystem.Services.Data;
@using HospitalPharmacyManagementSytem.Web.Infrastucture.Extensions;
@model PrescriptionViewModel
@{
    ViewData["Title"] = "Prescriptions";
}


<div class="col-md-4">
    <div class="card mb-3">
        <div class="card-body text-center">
            <h4>@Model.CreatedOn</h4>
            <h6>
                Patient Email:
                <b>@($"{Model.PatientEmail}") </b>
            </h6>
            <br />
            <a asp-area="" asp-controller="Prescription" asp-action="PrescriptionDetails" asp-route-id="@Model.Id"
               class="btn btn-success">Details</a>
            @*@if (User.Identity?.IsAuthenticated ?? false)
            {
                <a asp-controller="Drug" asp-action="Edit" asp-route-id="@Model.Id"
                   class="btn btn-warning">Edit</a>
                <a asp-controller="Drug" asp-action="Delete" asp-route-id="@Model.Id"
                   class="btn btn-danger">Delete</a>
                <p></p>
            }*@
        </div>
    </div>
</div>