HospitalPharmacyManagementSystem.Web/Areas/Admin/Controllers/DrugController.cs
using HospitalPharmacyManagementSystem.Services.Data.Interfaces;
using HospitalPharmacyManagementSystem.Web.Areas.Admin.ViewModels.Drug;
using HospitalPharmacyManagementSytem.Web.Infrastucture.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace HospitalPharmacyManagementSystem.Web.Areas.Admin.Controllers
{
    public class DrugController : BaseAdminController
    {
        private readonly IPharmacistService pharmacistService;
        private readonly IDrugService drugService;

        public DrugController(IPharmacistService pharmacistService, IDrugService drugService)
        {
            this.pharmacistService = pharmacistService;
            this.drugService = drugService;
        }

        public async Task<IActionResult> Mine()
        {
            var pharmacistId = await this.pharmacistService
                .GetPharmacistIdByUserIdAsync(this.User.GetId()!);

            MyDrugsViewModel model = new MyDrugsViewModel()
            {
                PrescribedDrugs = await this.drugService.AllByUserIdAsync(pharmacistId!)
            };

            return this.View(model);
        }
    }
}

HospitalPharmacyManagementSystem.Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HospitalPharmacyManagementSystem.Web.Areas.Admin.Controllers
{
    public class HomeController : BaseAdminController
    {
        public IActionResult Indexx()
        {
            return View();
        }
    }
}

HospitalPharmacyManagementSystem.Web/Controllers/HomeController.cs
namespace HospitalPharmacyManagementSystem.Web.Controllers
{
    using HospitalPharmacyManagementSystem.Services.Data.Interfaces;
    using HospitalPharmacyManagementSystem.Web.ViewModels.Home;
    using HospitalPharmacyManagementSytem.Web.Infrastucture.Extensions;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using System.Diagnostics;
    using static Common.GeneralAppConstants;

    public class HomeController : Controller
    {
        private readonly IDrugService drugService;
        private readonly IPharmacistService pharmacistService;
        public HomeController(IDrugService drugService, IPharmacistService pharmacistService)
        {
            this.drugService = drugService;
            this.pharmacistService = pharmacistService;
        }

        public async Task<IActionResult> Index()
        {
            if (this.User.IsInRole(AdminRoleName))
            {
                return this.RedirectToAction("Index", "Home", new { Area = AdminAreaName });
            }

            IEnumerable<IndexViewModel> model = await this.drugService.BestDealsAsync();
            string userId = this.User.GetId()!;
            bool isUserPharmacist = await this.pharmacistService
                .PharmacistExistsByUserIdAsync(userId);
            ViewBag.IsUserPharmacist = isUserPharmacist;
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(int statusCode)
        {

            if (statusCode == 400 || statusCode == 404)
            {
                return View("Error404");
            }

            if (statusCode == 401)
            {
                return View("Error401");
            }

            return View();
        }

        private async Task<bool> IsUserPharmacist()
        {
            string userId = this.User.GetId()!;
            bool isUserPharmacist = await this.pharmacistService
                .PharmacistExistsByUserIdAsync(userId);
            return ViewBag.IsUserPharmacist = isUserPharmacist;
        }
    }
}

HospitalPharmacyManagementSystem.Web/Views/Home/Error401.cshtml
@{
    ViewData["Title"] = "Error";
}

<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <br>
        <div class="row">
            <div class="col-10">
                <img src="https://media.istockphoto.com/photos/rubber-stamp-picture-id545992942?k=6&m=545992942&s=612x612&w=0&h=XD1kddQeDrbG9DEQQxGNf6_3snw4gdFZv8GqSFta6Is=" alt="Alternative image" class="img-thumbnail">
                <div class="text-left h4">
                    <p>Oops, you don't have access here.</p>
                </div>
                <div class="text-left h4">  Go back to <a asp-controller="Home" asp-action="Index">Home</a> Page</div>
            </div>
        </div>
    </div>
    <div class="col-3"></div>
</div>

HospitalPharmacyManagementSystem.Web/Views/Home/Error404.cshtml
@{
    ViewData["Title"] = "Error";
}

<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <br>
        <div class="row">
            <div class="col-10">
                <img src="https://www.publicdomainpictures.net/pictures/280000/velka/not-found-image-15383864787lu.jpg" alt="Alternative image" class="img-thumbnail">
                <div class="text-left h4">
                    <p>Oops, better check that URL. Page was not found.</p>
                </div>
                <div class="text-left h4">  Go back to <a asp-controller="Home" asp-action="Index">Home</a> Page</div>
            </div>
        </div>
    </div>
    <div class="col-3"></div>
</div>

HospitalPharmacyManagementSystem.Web/Views/Home/Index.cshtml
@using HospitalPharmacyManagementSystem.Services.Data.Interfaces;
@model IEnumerable<IndexViewModel>
@{
    ViewData["Title"] = "Home Page";
    var drugs = Model.ToList();
}

<div class="mt-2 p-5">
    <h1 class="display-6" style="text-align:center; font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;color:#f0a04b;font-weight:600">
        Welcome to DrugWise - the future of patient care!
    </h1>
    @if (!drugs.Any())
    {
        <p class="lead">
            There are no drugs in the system currently available!
        </p>
    }
    <hr class="my-4">
</div>

<div class="mb-5" style="width:300px;height:50px"></div>
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        @for (int i = 0; i < drugs.Count(); i++)
        {
            var drug = drugs[i];
            <div class="carousel-item @(i == 0 ? "active" : string.Empty)">
                <img class="d-block w-100" style="height:500px;background-color:#e1eedd"
                     src="@drug.ImageUrl" alt="@drug.BrandName">

                <div class="carousel-caption d-none d-md-block">
                    <h5>
                        <a class="btn btn-primary" asp-controller="Drug" aspaction="Details"
                       asp-route-id="@drug.Id"> @drug.BrandName</a>
                    </h5>
                </div>
            </div>
        }
    </div>
    <button class="carousel-control-prev" type="button" data-bstarget="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bstarget="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div class="mb-5"></div>

<div class="row">
    <div class="col-12 text-center" ">
        <button class="btn btn-primary" style="background-color: #23562b;" id="statistics_btn">Show Statistics</button>
    </div>
</div>

<div class="mt-4 p-5 d-none" id="statistics_box" style="background-color: #f0a04b">
    <div class="row">
        <h2 class="col-md-6 text-center" id="total_drugs"></h2>
        <h2 class="col-md-6 text-center" id="total_prescriptions"></h2>
    </div>
</div>

    @section Scripts
        {
    <script>statistics();</script>
}